apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: ywvw8a98x-nodejs 
  janus-idp.io/tekton: ywvw8a98x-nodejs
  backstage.io/kubernetes-id: ywvw8a98x-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ywvw8a98x-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml