apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ywvw8a98x-nodejs
  janus-idp.io/tekton: ywvw8a98x-nodejs
  backstage.io/kubernetes-id: ywvw8a98x-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ywvw8a98x-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
